version: '3.8'

services:
  web:
    build: .
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 