version: '3.8'

services:
  web:
    build: .
    ports:
      - "4173:4173"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    restart: unless-stopped 